Skip pymapd and pyspark for py38
conda-forge/ibis-framework-feedstock pull request #41
Opened 2020-04-14 00:27 UTC by xmnlab

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2020-04-14 00:27 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * Non noarch packages should have python requirement without any version constraints.
 * Non noarch packages should have python requirement without any version constraints.

2020-04-14 00:29 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * Non noarch packages should have python requirement without any version constraints.

2020-04-14 00:30 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2020-04-14 00:44 UTC, jreback commented
what is the purpose of actually building new packages here?

2020-04-14 01:18 UTC, xmnlab commented
the installation for python3.8 has unsolved dependencies:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
```

2020-04-14 01:30 UTC, xmnlab commented
@conda-forge-admin, please rerender

2020-04-14 01:51 UTC, xmnlab commented
@conda-forge-admin, please rerender

2020-04-14 03:02 UTC, xmnlab commented on recipe/meta.yaml
> +    - clickhouse-cityhash  # [not win]
the feedstock windows tests worked. but not sure how is the impact for the entire backend without this package.
ibis ci doesn't test clickhouse backend

2020-04-14 03:03 UTC, xmnlab commented
this PR is ready for review. thanks!

2020-04-14 03:36 UTC, jreback requested changes
i am note sure why you did this PR

2020-04-14 03:44 UTC, xmnlab commented
1. noarch-python building suppose the same dependencies for each python version and architecture, and for Ibis this condition is not true.
2. as the dependencies for python 3.8 is not corrected set, when install ibis for python 3.8 the building cannot solve the dependencies (see https://github.com/conda-forge/ibis-framework-feedstock/pull/41#issuecomment-613174035)

2020-04-14 03:57 UTC, jreback commented
let’s fix the actual CI first

this is completely orthogonal

2020-04-14 04:02 UTC, xmnlab commented
I think it is related to one of the currently problems we have on CI as condabuild job is not working and it is now using python 3.8 https://dev.azure.com/ibis-project/ibis/_build/results?buildId=2276&view=logs&j=179055bf-797c-5905-134a-4a7381d87002&t=e379731c-be9b-5a2e-f039-d0e3931908e6&l=138

2020-04-15 15:20 UTC, xmnlab commented
@jreback if there is no problem with this new change, could we have this merged? so I can check if it will fix the CI condabuild job

2020-04-15 16:00 UTC, jreback commented
i prefer to fix the actual co first
you changed quite a bit here so this needs a look. as well

2020-05-07 12:46 UTC, jreback approved these changes

2020-05-07 12:47 UTC, merged

2020-05-07 12:47 UTC, jreback commented
ok, merging to fix the main CI. this dependency is pretty odd to actually have the feedstock connected to the CI itself in the project.